seed: 42

dataset:
  root_dir: "D:/Desktop/Traffic-Vehicle-Classification/dataset_vit"

split:
  val_size: 0.2
  test_size: 0.0

experiments:

  V1:
    name: vit_b16_feature_extraction

    model:
      name: vit_b16
      strategy: feature_extraction
      pretrained: true

    data:
      image_size: 224
      batch_size: 16

    optimizer:
      name: AdamW
      lr: 0.001
      weight_decay: 0.0001

    scheduler:
      name: ReduceLROnPlateau
      mode: min
      factor: 0.1
      patience: 3

    training:
      epochs: 20

    checkpoint:
      load_from: null
      load_best: false